version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-org/order-service:dev
    environment:
      - ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/order_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # mount local code for hot reload
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"