version: "3.9"
services:
  app:
    image: ghcr.io/my-org/order-service:latest
    environment:
      - ENV=prod
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/order_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: order_db
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  prod_db_data: