# Generated by Django 5.2.6 on 2025-09-15 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True, unique=True)),
                ('user_status', models.CharField(blank=True, max_length=64, null=True)),
                ('inventory_status', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=64, null=True)),
                ('outcome', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
