name: Deploy

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Check if Deployment Secrets Exist
        id: check_secrets 
        run: |
          if [[ -n "${{ secrets.SERVER_HOST }}" && -n "${{ secrets.SERVER_USER }}" && -n "${{ secrets.SERVER_SSH_KEY }}" ]]; then
            echo "::notice::Deployment secrets for ${{ github.ref_name }} environment are set."
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "::warning::Deployment secrets for ${{ github.ref_name }} environment are MISSING. Skipping deployment."
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        if: ${{ steps.check_secrets.outputs.has_secrets == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Attempting deployment to ${{ github.ref_name }} environment..."
            cd /srv/order-service
            # Using ${{ github.ref_name }} to dynamically select the compose file
            # e.g., docker-compose.dev.yml for 'dev' branch, docker-compose.main.yml for 'main' branch
            docker-compose -f docker-compose.${{ github.ref_name }}.yml pull
            docker-compose -f docker-compose.${{ github.ref_name }}.yml up -d
            echo "Deployment script finished."