name: Deploy

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/order-service
            if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
              docker-compose -f docker-compose.dev.yml pull
              docker-compose -f docker-compose.dev.yml up -d
            elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
              docker-compose -f docker-compose.prod.yml pull
              docker-compose -f docker-compose.prod.yml up -d
            fi